### ISSUE TITLE
Installing an older version of samtools in smart (Lidia say it works better with big files) 

### ISSUE THREAD

**Issue by pjmramond** [marbits-icm/marbits-public#14]
Could you please install this version in smart?

https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2

**Comment by pablo-icm** [comment]
Well... It is done. It is not super advisable to run such an old version of any software, but you asked and I provide. Use at your own risk.

```
spack load samtools@1.9
```

should work.
