### ISSUE TITLE
issues with my marbits user 

### ISSUE THREAD

**Issue by lidmontiel** [marbits-icm/marbits-public#2]
Holi, 

*Estreno els tickets!*

Estem veient que el meu usuari a Marbits no funciona (no puc fer cap `ls -f` enlloc, no només als lustres) perquè creiem que dec tenir algun path export als meus arxius .bashprofile o .bashrc que deuen portar a algun disc trencat o al lustre afectat.
Em podrieu silenciar aquestes variables d'aquests arxius ocults aviam si es soluciona? Els tinc al meu `/home/lmontiel`.

O el problema és degut a això, o és que tinc tants processos zombis d'haver tancat la sessió bruscament que el meu user em dóna aquests problemes.

Mercis mil,

L.

**Comment by xabilopalf** [comment]
Kaixo Lidia,

Yo, no se si será por motivos similares, pero llevo dos días sin poder entrar a MARBITS. Realmente sí que puedo, pero luego no puedo listar nada, ni un simple `ls -l` .  

Además, una colaboradora de Argentina que tengo está en el mismo problema. Y que yo sepa alguna que otra persona más también. 

Zinez,
X.

**Comment by lidmontiel** [comment]
Ok.

Well, there are some users who don’t have the same experience. We believe this could be related to my environment config in the `.bash_profile` or `.bashrc` files (and perhaps Xabi and other users have the same problem). I was wondering if an admin could modify these files to resolve this temporarily, so that we can access the system. 

Thks.

**Comment by pablo-icm** [comment]
Solved [here](https://github.com/marbits-icm/marbits-public/discussions/4#discussioncomment-11476137). If there's still something going on, please report there.
